import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Link from 'next/link';
import Layout from '../components/layout';
import { NextPageWithLayout } from '../types/page';

// TODO: generate sitemap

const Home: NextPageWithLayout = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.heading}> Welcome to Lusift!</h1>
        <Link href="/docs/overview" as={`/docs/overview`}>
          <a className="hover:underline">Documentation</a>
        </Link>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  );
}

Home.getLayout = (page) => {
  return (
    <Layout>
      {page}
    </Layout>
  );
}

export default Home
